[package]
name = "db"
version = "0.1.0"
edition = "2024"

[dependencies]
anyhow = "1.0.72"
futures = "0.3.28"
tokio = { version = "1.29.1", features = ["full"] }
sqlx = { version = "0.6.3", features = ["runtime-tokio-native-tls", "sqlite"] }
dotenv = "0.15.0"
